name: Run Tests
on:
  - push
  - pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.9'
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: |
          pip install pipenv
          pipenv install
      - run: pipenv run test-docs
      - run: pipenv run test-schema
      - run: pipenv run test-geojson
      - run: pipenv run test-geoparquet
